name: link

on: [push]

jobs:
  link-linux:
    name: Link assets on Linux
    runs-on: ubuntu-24.04

    steps:
      - name: Check out files
        uses: actions/checkout@main

      - name: Setup OAT
        uses: diamante0018/setup-oat@main
        with:
          version: "0.14.1"

      - name: Link assets
        run: |
          Linker -v arena

      - name: Upload mod.ff
        uses: actions/upload-artifact@main
        with:
          name: arena
          path: |
            zone_out/arena/mod.ff
