name: link

on: [push]

env:
  OAT_VERSION: "0.21.0"

jobs:
  link-linux:
    name: Link assets on Linux
    runs-on: ubuntu-latest
    container: ubuntu:noble

    steps:
      - name: Check out files
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          dpkg --add-architecture i386
          apt-get update
          apt-get -y install libstdc++-13-dev:i386

      - name: Setup OAT
        uses: diamante0018/setup-oat@main
        with:
          version: ${{ env.OAT_VERSION  }}

      - name: Link assets
        run: |
          Linker -v arena

      - name: Upload mod.ff
        uses: actions/upload-artifact@main
        with:
          name: arena
          path: |
            zone_out/arena/mod.ff
